version: "3.2"
services:
  worker:
    image: postnikovlab4-worker-test
    build:
      dockerfile: worker/worker.Dockerfile
      context: ""
    container_name: "worker-test"
    restart: "on-failure"
    env_file:
      - worker/worker.env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: "redis-test"
    expose:
      - "6379"
    restart: "no"

  test:
    image: postnikovlab4-test
    build:
      dockerfile: test.Dockerfile
      context: ""
    container_name: "test"
    restart: "on-failure"
    depends_on:
      - redis
      - worker
